### ISSUE TITLE
Looks like an amamzing paper! When is the code release?

### ISSUE THREAD

**Issue by fnuabhimanyu8713** [yufu-wang/tram#1]

**Comment by yufu-wang** [comment]
We are working on releasing the code in the next couple of weeks. Sorry for the wait. I can update you here when it's released.

**Comment by andrewnc** [comment]
Great work! Let us know if we can help to make the code release smooth. We'd be glad to chip in as needed.

**Comment by HonglinChu** [comment]
good work，the code will be released next week？

**Comment by FeyaM** [comment]
期待发布！加油！

**Comment by HonglinChu** [comment]
Thank you, when the pretrained model will be released?

**Comment by yufu-wang** [comment]
Thank you for your patience. We have put out an initial release, including our pretrained model. To get the model and other thirdparty checkpoints, please refer to the "Prepare data" in the README.
