### ISSUE TITLE
how about DPVO instead of DROID?

### ISSUE THREAD

**Issue by Dong09** [yufu-wang/tram#15]
thank you for your awesome working !
I found in your repositories that DPVO and DROID work similarly, and DPVO may work better, I was wondering how DPVO can be used instead of DROID? DROID produces some parameters that DPVO does not, what should I do? I would appreciate it very much if you could have your answer.

**Comment by Dong09** [comment]
@yufu-wang

**Comment by yufu-wang** [comment]
I think [wham](https://arxiv.org/abs/2312.07531) did an ablation and DROID give better/similar results to DPVO, in term of recovering the humans. But please feel free to give it a try with our method.

**Comment by Dong09** [comment]
thanks for your reply.
I would like to ask whether the "pred_rotmat" inferred by the vimo model is a rotation matrix of a global coordinate system or a local coordinate system. Also What does the "pred_pose" in the vimo results mean?
Thanks again.

**Comment by YanMeng1996** [comment]
Hi, may I ask if you have confirmed the specific meaning of pred_rotmat and which coordinate system it is in, thanks.
