### ISSUE TITLE
Problem of Installation

### ISSUE THREAD

**Issue by Marlod390** [yufu-wang/tram#2]
Dear Authors,

Thanks for your work and releasing code. But I encountered some problems during installation and would like to ask for your help.

The first problem is about the installation of pytorch_scatter. If using `conda install pytorch-scatter -c pyg`, the lower versions of pytorch and cuda will be automatically installed. And command `pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cu118.html` works fine on my PC.

The second is about the installation of DROID-SLAM. Since the project relies on the old Eigen, a lot of compatibility errors were reported. I checked the original project and couldn't find a solution. If possible, could you please share some experience on installing DROID-SLAM?
A error I encountered recently is `/usr/local/cuda-11.8/include/crt/common_functions.h:74:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions`

Thanks in advance

**Comment by yufu-wang** [comment]
Thank you trying out the code. 
1. "conda install pytorch-scatter -c pyg" seems to work fine for us. It's tested with torch-2.0.0 and Cuda-11.8 on ubuntu.
2. I updated the "Eigen" submodule. Please clone the repo again. 
3. In addition, I updated "install.sh" a little, to install cuda-11.8 (if you needed) and fix detectron2 version to counter a recent bug. 
Please give it another try.

**Comment by Marlod390** [comment]
Now the installation runs smoothly. For me i have to install lietorch using pip, otherwise it will report `ImportError: cannot import name 'SE3' from 'lietorch'`. Anyway, the code produces good result on the demo video.  Thanks a lot for your help!

**Comment by WangJYao** [comment]
`E:\project\tram\thirdparty\DROID-SLAM\thirdparty\eigen\Eigen\src/Core/PlainObjectBase.h(963): error: function "Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::operator=(const Eigen::Block<Eigen::Matrix<int, -1, 1, 0, -1, 1>, -1, -1, false> &) [with XprType=Eigen::Matrix<int, -1, 1, 0, -1, 1>, BlockRows=-1, BlockCols=-1, InnerPanel=false]" (declared implicitly) cannot be referenced -- it is a deleted function
`
Eigen have problems
