### ISSUE TITLE
这个网站的压缩包打不开了！

### ISSUE THREAD

**Issue by qfb594** [yufu-wang/tram#4]
gdown https://drive.google.com/uc?id=0B-ePgl6HF260NzQySklGdXZyQzA
unzip Barn.zip
rm Barn.zip
文档里需要的这个网站  打不开了  可以重新给一个下载链接？

**Comment by yufu-wang** [comment]
Hi I think this is the wrong repo for the issue. We don't have "Barn.zip". Please reopen if I was mistaken.
